CREATE TABLE DISPLAYSETS
(
	ID 				INT PRIMARY KEY,
	SEITE			TEXT,
	NUMMER			INT,
	URL				TEXT,
	AKTIV			INT,
	REFRESH 		INT,
	REFRESHAKTIV 	INT,
	VONBIS			TEXT,
	MARGINLEFT		TEXT,
	MARGINRIGHT		TEXT,
	MARGINTOP		TEXT,
	MARGINBOTTOM	TEXT
);

CREATE TABLE WIDGETS
(
	ID 				INT PRIMARY KEY,
	NAME			TEXT,
	TYP				TEXT,
	AKTIV			INT,
	URL				TEXT,
	valign			TEXT,
	align			TEXT,
	vmargin 		TEXT,
	margin			TEXT,
	width			TEXT,
	height			TEXT
);

CREATE TABLE SETTINGS
(
	ID 				INT PRIMARY KEY,
	NAME			TEXT,
	VALUE			TEXT
);